### PR TITLE
fix: pin babel-preset-es2015, update breaks build

### PR DESCRIPTION
**Pull request by chrisprice**
Caused by rollup/rollup-plugin-babel#71

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Is it worth pinning all versions? We seems to receive accidental breaking changes more often than benefits from accepting a range of version numbers.

**Comment by chrisprice** [comment]
Working on an alternative :+1:

**Comment by chrisprice** [comment]
https://github.com/d3fc/d3fc-scripts

**Comment by chrisprice** [comment]
Was meaning to do it anyway but with the flood of Greenkeeper mails, it seems worth bumping up the priority queue!

**Pull request merged**
